version: "3.4"

services:
    app:
        container_name: app
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/prod/app/Dockerfile
            target: runner
        env_file:
            - .env
        ports:
            - ${DOCKER_APP_PORT:-3000}:3000
        depends_on:
            - mongo
        stdin_open: true
        tty: true
    indexer:
        container_name: indexer
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/prod/indexer/Dockerfile
            target: runner
        env_file:
            - .env
        volumes:
            - ./servers/indexer/logs:/app/indexer/logs:rw
        depends_on:
            - mongo
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        restart: unless-stopped
        environment:
            - MONGO_INITDB_DATABASE=${MONGODB_DATABASE:-metadata}
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME:-marketplace}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-CHANGEME!}
        volumes:
            - mongodata:/data/db
            - ./docker/dev/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports:
            - 27017-27019:27017-27019
volumes:
    mongodata:
