version: "3"

services:
    app:
        container_name: app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/app
        ports:
            - 3000:3000
        links:
            - mongo

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=metadata
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
        volumes:
            - ./data:/data/db
        ports:
            - 27017-27019:27017-27019
