version: "3.4"

services:
    app:
        container_name: app
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/prod/app/Dockerfile
            target: runner
        env_file:
            - .env
        ports:
            - 3000:8000
        depends_on:
            - mongo
    indexer:
        container_name: indexer
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/prod/indexer/Dockerfile
            target: runner
        env_file:
            - .env
        volumes:
            - ./indexer/logs:/app/indexer/logs:rw
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        restart: unless-stopped
        environment:
            - MONGO_INITDB_DATABASE=metadata
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
        volumes:
            - ./data:/data/db:rw
        ports:
            - 27017-27019:27017-27019
